### ISSUE TITLE
Cp1251 support?

### ISSUE THREAD

**Issue by projct1** [elvanto/litemoji#14]
Hi! It is possible to convert cp1251 string "🔥 - это огонь" into "```&#128293;``` - это огонь"?
Now ```LitEmoji::encodeHtml("🔥 - это огонь")``` returns " - это огонь" :(

**Comment by joshmcrae** [comment]
Hi there! With the following test code I get `&#x1F525; - это огонь`.

```php
<?php
  
require_once(__DIR__ . '/vendor/autoload.php');

echo \LitEmoji\LitEmoji::encodeHtml("🔥 - это огонь");
```

Could you check that it's converting to a shortcode correctly by calling `LitEmoji::encodeShortcode(...)`.

**Comment by projct1** [comment]
Sry, my fault. I converted all data from utf8 before call encodeHtml :)
