### ISSUE TITLE
Request: List

### ISSUE THREAD

**Issue by daniel-lucio** [elvanto/litemoji#24]
is there somewhere a list of full shortcodes with a sample of the output?

**Comment by joshmcrae** [comment]
Hi @daniel-lucio, we're using [milesj/emojibase](https://github.com/milesj/emojibase) as a dev dependency and periodically update our library with the shortcode / codepoint mappings from that package.

They provide their database in a browsable format [here](https://emojibase.dev/emojis?) which will show you the available shortcodes and resulting glyphs.
