### ISSUE TITLE
Missing emoji in regex

### ISSUE THREAD

**Issue by chochold** [elvanto/litemoji#25]
Hi, 
there is missing emoji Shopping trolley (https://unicode-table.com/en/1F6D2/) in regex:
https://github.com/elvanto/litemoji/blob/master/src/LitEmoji.php
`const MB_REGEX = '/(
    		     \x23\xE2\x83\xA3               # Digits
    		     [\x30-\x39]\xE2\x83\xA3
    		   | \xE2[\x9C-\x9E][\x80-\xBF]     # Dingbats
    		   | \xF0\x9F[\x85-\x88][\xA6-\xBF] # Enclosed characters
    		   | \xF0\x9F[\x8C-\x97][\x80-\xBF] # Misc
    		   | \xF0\x9F\x98[\x80-\xBF]        # Smilies
    		   | \xF0\x9F\x99[\x80-\x8F]
    		   | \xF0\x9F\x9A[\x80-\xBF]        # Transport and map symbols
    		   | \xF0\x9F[\xA4-\xA7][\x80-\xBF] # Supplementary symbols and pictographs
    		)/x';`

UTF-8 (hex) for shopping trolley is	0xF0 0x9F 0x93 0xA6

**Comment by joshmcrae** [comment]
Hi @chochold, thanks for brining this to our attention!

This has been fixed in release [4.0.2](https://github.com/elvanto/litemoji/releases/tag/4.0.2).
