### ISSUE TITLE
Remove emoji

### ISSUE THREAD

**Issue by KarelWintersky** [elvanto/litemoji#27]
How to remove found emoji ?

**Comment by joshmcrae** [comment]
Hi @KarelWintersky,

Are you looking for a way to remove all emoji from a string or something else? This library currently on deal with converting emoji from on format to another. We welcome PRs to implement new functionality.

A simple approach might look like the following.

```php
$shortcodes = LitEmoji::encodeShortcode('Some text 😊 including emoji 🚀');
$text = preg_replace('/\:\w+\:/', '', $shortcodes);
```

**Comment by KarelWintersky** [comment]
I am developing a news site. Editors sometimes copy and paste articles directly from the Internet, without revision. Naturally, emojis sometimes come across in the text, and their use is prohibited by the internal policy of the resource.

Your library is popular enough and actively supported that I will use it rather than invent my own regular expression every time I find a new emoji.

I use it to remove emoji from text.

Sorry, I used google to translate this text. 

My code is absolutly identical :-)
```
public static function removeEmoji(string $text)
{
    $replacement = Config::get('ADMIN.ARTICLE.EMOJI_REPLACMENT') ?: '';
    return Regex::replace('/:\w+:/m', $replacement, LitEmoji::encodeShortcode($text))->result();
}
```
I'll make PR a bit later, thank you.

**Comment by KarelWintersky** [comment]
#28 PR requested
