### ISSUE TITLE
2 emojies not matched by MB_REGEX

### ISSUE THREAD

**Issue by Spirit55555** [elvanto/litemoji#30]
The following 2 emojis are not matched by MB_REGEX:
https://emojipedia.org/balance-scale/
https://emojipedia.org/hammer-and-pick/

**Comment by joshmcrae** [comment]
Hi @Spirit55555, thanks for opening an issue. The regex found [here](https://github.com/elvanto/litemoji/blob/master/src/LitEmoji.php#L7) is responsible for identifying emoji within specific codepoint ranges. The emoji you're interested in are likely outside of these ranges, so the regex simply needs to be updated to accommodate them.

We have little time to dedicate to this project right now, but will happily accept pull requests.

I've left this issue open for the moment.
