### ISSUE TITLE
Missing geometric emojis in regex

### ISSUE THREAD

**Issue by engram-design** [elvanto/litemoji#34]
Looks like there's lack of support for a few geometric emojis in the `MB_REGEX` constant. For reference - https://unicode.org/emoji/charts/full-emoji-list.html#geometric
 🟠  🟡  🟢   🟣  🟤  ⚫  ⚪  🟥  🟧  🟨  🟩  🟦  🟪  🟫  ⬛  ⬜  ◼  ◻ 

The following _are_ included already:
🔴  🔵

This is despite all these already appearing in the [shortcodes-array](https://github.com/elvanto/litemoji/blob/master/src/shortcodes-array.php) file, it just doesn't match against the regex pattern.

I'd love to put a PR together, but I'm a novice with Regex at best - sorry!.

Additionally, it'd be neat if this constant could be changed to a static property to allow other to modify the regex to save you having to update it all the time. So we could do:

```php
LitEmoji::$MB_REGEX = ...
```

**Comment by joshmcrae** [comment]
Thanks for bringing this to our attention @engram-design. We've refactored the regex used to match emoji and the way that it is generated.

[Pre-release 4.3.0](https://github.com/elvanto/litemoji/releases/tag/4.3.0-alpha) includes these changes.

Would you mind giving this version a test and we'll do a proper release soon?

**Comment by engram-design** [comment]
That's a great solution @joshmcrae and everything is working well on my end with those changes!

**Comment by joshmcrae** [comment]
Thanks for testing! Now released as [4.3.0](https://github.com/elvanto/litemoji/releases/tag/4.3.0).
