### ISSUE TITLE
Kazakhstan flag not working

### ISSUE THREAD

**Issue by Alexell** [elvanto/litemoji#37]
Hello.
**Code:** `LitEmoji::encodeUnicode(':kz:');`
**Expected:** 🇰🇿
**Received:** :kz:

**Version litemoji:** 4.3.0
**PHP 8.1**

**Comment by joshmcrae** [comment]
Hi @Alexell, a list of supported short codes can be found in [src/shortcodes-array.php](https://github.com/elvanto/litemoji/blob/master/src/shortcodes-array.php) (which uses data from [miles/emojibase](https://github.com/milesj/emojibase)).

The shortcode for this flag is `:flag-kz:`
