### ISSUE TITLE
unicorn emoji

### ISSUE THREAD

**Issue by Inkognitoo** [elvanto/litemoji#5]
Emoji «🦄» do not convert by `\LitEmoji\LitEmoji::encodeShortcode('🦄')` 
https://emojipedia.org/unicorn-face/

**Comment by Inkognitoo** [comment]
And ✊️ too 
https://emojipedia.org/raised-fist/

**Comment by joshmcrae** [comment]
Support for the blocks where these emoji are found was added with b30d679 (release 1.4.1).

**Comment by kl3jvi** [comment]
:unicorn:
