### ISSUE TITLE
PHP 5.6 constant used

### ISSUE THREAD

**Issue by brandonkelly** [elvanto/litemoji#7]
LitEmoji's composer.json says it requires PHP 5.4+:

https://github.com/elvanto/litemoji/blob/af94de6becfbc2f4d9c52e1142183146fd087f36/composer.json#L7-L9

However v1.4 is using the `ARRAY_FILTER_USE_KEY ` constant, which is only available in PHP 5.6+ (7c0276dd0e5004bc78b7865e12030f3d2b6b8d0e).

https://github.com/elvanto/litemoji/blob/af94de6becfbc2f4d9c52e1142183146fd087f36/src/LitEmoji.php?utf8=%E2%9C%93#L200

So either that code should be updated to not use a PHP 5.6+ constant, or composer.json should be updated to require PHP 5.6+.

**Comment by joshmcrae** [comment]
Hi Brandon, thanks for bringing this to our attention.

Fixed with #9.
